version: '3.8'

services:
  csv-netsuite-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
